---
title: "Research"
---

<br>

# {.tabset .tabset-fade}

## Projects

<br>

<font color="#18BC9C"><h2>Publications</h2></font>

#### __Blue Carbon: Coastal Ecosystems, Their Carbon Storage, and Potential for Reducing Emissions__

with [Juha Siikamaki](https://www.researchgate.net/profile/Juha_Siikamaeki), [James Sanchirico](http://www.des.ucdavis.edu/faculty/Sanchirico/Index.htm), [Sunny Jardine](https://smea.uw.edu/faculty/sunny-jardine-ph-d/), and [Daniel Morris](https://www.linkedin.com/in/dfmorris/)

Write summary of paper here.

<br>

<font color="#18BC9C"><h2>Working Papers</h2></font>

---

<br>

#### __For the Benefit of California Electricity Ratepayers: Electricity Sector Options for the Use of Allowance Value Created under California's Cap-and-Trade Program__

with [Dallas Burtraw](https://www.rff.org/people/dallas-burtraw/) and [Sarah Jo Szambelan](https://www.spur.org/about/staff/sarah-jo-szambelan)

Write summary of paper here.

<br>

#### __California's New Gold: A Primer on the Use of Allowance Value Created Under the CO2 Cap-and-Trade Program__

with [Dallas Burtraw](https://www.rff.org/people/dallas-burtraw/) and [Sarah Jo Szambelan](https://www.spur.org/about/staff/sarah-jo-szambelan)

Write summary of paper here.

<font color="#18BC9C"><h2>In Progress</h2></font>

---
#### __The effects of communal land certification on land use: Evidence from Mexico__
with [Elisabeth Sadoulet](https://are.berkeley.edu/esadoulet/), [Alain de Janvry](https://are.berkeley.edu/alain/), [Marco Gonzalez-Navarro](https://are.berkeley.edu/users/marco-gonzalez-navarro), and (Daley Kutzman)[https://www.economics.northwestern.edu/people/directory/daley-kutzman.html]


#### __Do consumers value clean drinking water?__

Write summary of paper here.


#### __Heads or Curtails?: The Impact of Water Rights Supply Curtailments on Junior Rights Holders in California's Central Valley__

Write summary of paper here.



## Presentations

<br>

__The economic impact of critical-habitat designation: Evidence from vacant-land transactions__
<br> The Occasional Workshop (UCSB), November 2018
<br><br>

